SET MODE MYSQL;

-- 用户
CREATE TABLE `al_user` (
  `user_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(100) COMMENT '密码',
  `salt` varchar(20) COMMENT '盐',
  `email` varchar(100) COMMENT '邮箱',
  `status` tinyint COMMENT '状态  0：禁用  1：正常',
  `create_time` datetime COMMENT '创建时间',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
);

-- 用户Token
CREATE TABLE `user_token` (
  `user_id` bigint(20) NOT NULL,
  `token` varchar(50) NOT NULL COMMENT 'token',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `token` (`token`)
);
